arantes:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      host: docker-local-mongo-1
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarch